In [1]:
import numpy as np
import pandas as pd
import os

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [2]:
np.random.seed(42)
n = 1_000_000

df = pd.DataFrame({
    "edad": np.random.normal(40, 12, n),
    "ingresos": np.random.lognormal(10, 0.5, n),
    "altura": np.random.normal(170, 10, n),
    "experiencia": np.random.randint(0, 41, n),
    "categoria": np.random.choice(["A", "B", "C", "D", "E"], n)
})

print("Dataset de 1M generado.")

Dataset de 1M generado.

In [3]:
print("Dimensiones:", df.shape) # Debería mostrar (1000000, 5)
df.head()

Dimensiones: (1000000, 5)

        edad      ingresos      altura  experiencia categoria
0  45.960570  23970.661583  180.647224           24         A
1  38.340828  20728.138874  165.032868           29         E
2  47.772262  39273.789308  171.292602            8         B
3  58.276358  24344.053627  155.203066            3         B
4  37.190160  33938.500156  166.901527           19         E

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   edad         1000000 non-null  float64
 1   ingresos     1000000 non-null  float64
 2   altura       1000000 non-null  float64
 3   experiencia  1000000 non-null  int32
 4   categoria    1000000 non-null  object
dtypes: float64(3), int32(1), object(1)
memory usage: 34.3+ MB

In [5]:
df.describe()

                 edad        ingresos          altura     experiencia
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000
mean        39.980803    24964.400262      170.001880       20.000157
std         12.002262    13328.646324        9.997704       11.826640
min        -17.953232     2159.842568      120.198541        0.000000
25%         31.874999    15719.449479      163.258851       10.000000
50%         39.988052    22027.900394      170.009715       20.000000
75%         48.079711    30855.990882      176.753000       30.000000
max         96.147389   246178.303826      220.323742       40.000000

In [6]:
df["categoria"].value_counts()

categoria
B    200600
D    200316
A    199793
E    199725
C    199566
Name: count, dtype: int64

In [7]:
df.to_parquet(
    "../data/dataset_1M.parquet",
    index=False
)
print("dataset_1M.parquet guardado .")

dataset_1M.parquet guardado .

In [8]:
n = 5_000_000
np.random.seed(42)

df = pd.DataFrame({
    "edad": np.random.normal(40, 12, n),
    "ingresos": np.random.lognormal(10, 0.5, n),
    "altura": np.random.normal(170, 10, n),
    "experiencia": np.random.randint(0, 41, n),
    "categoria": np.random.choice(["A", "B", "C", "D", "E"], n)
})

In [9]:
df.shape

(5000000, 5)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 5 columns):
 #   Column       Dtype
---  ------       -----
 0   edad         float64
 1   ingresos     float64
 2   altura       float64
 3   experiencia  int32
 4   categoria    object
dtypes: float64(3), int32(1), object(1)
memory usage: 171.7+ MB

In [11]:
df.describe()

               edad      ingresos        altura   experiencia
count  5.000000e+06  5.000000e+06  5.000000e+06  5.000000e+06
mean   3.999782e+01  2.495966e+04  1.700005e+02  1.999638e+01
std    1.200138e+01  1.330275e+04  1.000088e+01  1.183172e+01
min   -1.976175e+01  1.639865e+03  1.188103e+02  0.000000e+00
25%    3.189826e+01  1.571939e+04  1.632550e+02  1.000000e+01
50%    4.000047e+01  2.202656e+04  1.700080e+02  2.000000e+01
75%    4.809160e+01  3.086169e+04  1.767452e+02  3.000000e+01
max    1.004057e+02  2.995457e+05  2.207648e+02  4.000000e+01

In [12]:
df.to_parquet(
    "../data/dataset_5M.parquet",
    index=False
)

In [13]:
print("¿Existe dataset_1M?:", os.path.exists("../data/dataset_1M.parquet"))
print("¿Existe dataset_5M?:", os.path.exists("../data/dataset_5M.parquet"))

¿Existe dataset_1M?: True
¿Existe dataset_5M?: True